apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dex
  namespace: dex
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - dex.lab.kubecarrier.io
      secretName: dex-tls
  rules:
    - host: dex.lab.kubecarrier.io
      http:
        paths:
          - path: /
            backend:
              serviceName: dex
              servicePort: http
