
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /joke-e2e-kubebuilder-io-webhook
  failurePolicy: Fail
  name: mcronjob.kb.io
  rules:
  - apiGroups:
    - e2e.kubebuilder.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - joke
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-batch-tutorial-kubebuilder-io-v1-cronjob
  failurePolicy: Fail
  name: vcronjob.kb.io
  rules:
  - apiGroups:
    - batch.tutorial.kubebuilder.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cronjobs
