
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-master-kubecarrier-io-v1alpha1-managementcluster
  failurePolicy: Fail
  name: vmanagementcluster.kubecarrier.io
  rules:
  - apiGroups:
    - master.kubecarrier.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - managementclusters
